/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedReleaseResponse {
  artist?: string;
  id?: number;
  rate?: number;
  reference?: string;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
