/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedReleaseResponse } from '../models/borrowed-release-response';
export interface PageResponseBorrowedReleaseResponse {
  content?: Array<BorrowedReleaseResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
