/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReleaseResponse {
  archived?: boolean;
  artist?: string;
  cover?: string;
  id?: number;
  owner?: string;
  rate?: number;
  reference?: string;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
