/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReleaseRequest {
  artist: string;
  id?: number;
  reference: string;
  shareable?: boolean;
  synopsis: string;
  title: string;
}
