/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ReleaseService } from './services/release.service';
export { FeedbackService } from './services/feedback.service';
export { AuthenticationService } from './services/authentication.service';
