/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReleaseResponse } from '../../models/release-response';

export interface FindReleaseById$Params {
  'release-id': number;
}

export function findReleaseById(http: HttpClient, rootUrl: string, params: FindReleaseById$Params, context?: HttpContext): Observable<StrictHttpResponse<ReleaseResponse>> {
  const rb = new RequestBuilder(rootUrl, findReleaseById.PATH, 'get');
  if (params) {
    rb.path('release-id', params['release-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReleaseResponse>;
    })
  );
}

findReleaseById.PATH = '/releases/{release-id}';
